#!/usr/bin/env bash
# =============================================================================
# backup-zip-to-secrets-env.sh
# -----------------------------------------------------------------------------
# Convert a DeltaGlider Proxy backup zip (GET /_/api/admin/backup) into a filled
# `secrets.env` for the IaC deployment.
#
# RUN THIS YOURSELF, LOCALLY. It reads live production secrets from the zip and
# writes them to secrets.env (gitignored). Secret values never leave your
# machine. Nothing is printed to stdout except progress + which keys were filled
# (never the values).
#
# Step 0 — pull a fresh backup from prod (do this yourself; needs a prod admin
# session cookie or bootstrap login):
#     curl -fsS -b prod-cookies.txt https://<PROD>/_/api/admin/backup -o prod-backup.zip
#   (or use the admin GUI: Settings → Backup → Download.)
#
# Usage:
#     ./backup-zip-to-secrets-env.sh prod-backup.zip [secrets.env]
#
# Requires: unzip, jq.
# =============================================================================
set -euo pipefail

ZIP="${1:?usage: $0 <backup.zip> [out.env]}"
OUT="${2:-secrets.env}"

command -v jq    >/dev/null || { echo "need jq";    exit 1; }
command -v unzip >/dev/null || { echo "need unzip"; exit 1; }
[[ -f "$ZIP" ]] || { echo "no such file: $ZIP"; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
unzip -o -q "$ZIP" -d "$TMP"

SEC="$TMP/secrets.json"
IAM="$TMP/iam.json"
[[ -f "$SEC" ]] || { echo "backup has no secrets.json"; exit 1; }
[[ -f "$IAM" ]] || { echo "backup has no iam.json";    exit 1; }

# Helper: emit KEY=VALUE, pulling VALUE from a jq filter against a file.
# Logs the key name only (never the value).
#
# The output is a docker-compose `env_file` (KEY=value, value taken LITERALLY —
# no shell quoting). It is NOT meant to be `source`d by a shell. We reject any
# value containing a newline or other control char: such a value can't live on a
# single env-file line and (if the file were ever sourced) a `$(...)`/backtick
# would be inert here only because the value is literal — a control char is the
# one thing that breaks the literal contract, so fail loudly instead.
emit() {  # emit <ENV_KEY> <file> <jq-filter>
  local key="$1" file="$2" filter="$3" val
  val="$(jq -r "$filter // empty" "$file")"
  if printf '%s' "$val" | LC_ALL=C grep -q '[[:cntrl:]]'; then
    warn "  ✗ $key: value contains a control character / newline — refusing to write"
    exit 1
  fi
  printf '%s=%s\n' "$key" "$val" >> "$OUT"
  if [[ -n "$val" ]]; then echo "  ✓ $key"; else echo "  ⚠ $key (empty in backup)"; fi
}

# Map a DGP iam_users NAME → the secrets.env var name used in deltaglider_proxy.yaml.
# Keep this in sync with secrets.env.template.
user_var() {
  case "$1" in
    "Simone Scarduzio") echo "USER_SIMONE_SECRET" ;;
    "ror-ci-rw")        echo "USER_ROR_CI_RW_SECRET" ;;
    "ror-ci-ro")        echo "USER_ROR_CI_RO_SECRET" ;;
    "rorkbn-ci")        echo "USER_RORKBN_CI_SECRET" ;;
    "xperi")            echo "USER_XPERI_SECRET" ;;
    "legacy-admin")     echo "USER_LEGACY_ADMIN_SECRET" ;;
    *)                  echo "" ;;   # OAuth-provisioned / dropped (test) / unknown → skip
  esac
}

: > "$OUT"
chmod 600 "$OUT"
{
  echo "# Generated by backup-zip-to-secrets-env.sh from $ZIP"
  echo "# CONTAINS LIVE SECRETS — never commit (see .gitignore)."
  echo
  echo "# ── Native DGP_* env ──"
} >> "$OUT"

echo "Writing $OUT (filled keys logged, values hidden):"

emit DGP_BOOTSTRAP_PASSWORD_HASH  "$SEC" '.bootstrap_password_hash'
{ echo "DGP_CONFIG=/etc/deltaglider_proxy/config.yaml"
  echo "DGP_LISTEN_ADDR=0.0.0.0:9000"
  echo
  echo "# ── \${VAR} placeholders substituted into the YAML ──"
} >> "$OUT"

# Bootstrap SigV4 pair (access.* in the backup). REQUIRED for cold start — the
# startup auth gate runs before declarative IAM is reconciled, so the proxy
# needs these (or authentication:none) to come up on a fresh DB.
emit BOOTSTRAP_ACCESS_KEY_ID      "$SEC" '.access.access_key_id'
emit BOOTSTRAP_SECRET_ACCESS_KEY  "$SEC" '.access.secret_access_key'

# Named-backend (Hetzner) creds — inline in the YAML, so ${VAR}, not DGP_BE_AWS_*.
# Prefer the per-named-backend secret; fall back to the singular storage.* (same
# upstream) for older backups that don't carry storage_backends.
emit BACKEND_HETZNER_ACCESS_KEY_ID     "$SEC" '.storage_backends.HetznerHelsinki1.access_key_id // .storage.access_key_id'
emit BACKEND_HETZNER_SECRET_ACCESS_KEY "$SEC" '.storage_backends.HetznerHelsinki1.secret_access_key // .storage.secret_access_key'

# OAuth client secret (provider name "goog" → GOOGLE_OAUTH_CLIENT_SECRET).
emit GOOGLE_OAUTH_CLIENT_SECRET   "$SEC" '.oauth_client_secrets.goog'

# Per-user secret access keys, mapped by user NAME.
echo "  --- per-user secret keys ---"
while IFS=$'\t' read -r uname; do
  var="$(user_var "$uname")"
  [[ -n "$var" ]] || { echo "  · skip '$uname' (OAuth-provisioned or not in IaC)"; continue; }
  val="$(jq -r --arg n "$uname" '.users[] | select(.name==$n) | .secret_access_key // empty' "$IAM")"
  if printf '%s' "$val" | LC_ALL=C grep -q '[[:cntrl:]]'; then
    warn "  ✗ $var: value contains a control character / newline — refusing to write"
    exit 1
  fi
  printf '%s=%s\n' "$var" "$val" >> "$OUT"
  if [[ -n "$val" ]]; then echo "  ✓ $var"; else echo "  ⚠ $var (empty)"; fi
done < <(jq -r '.users[].name' "$IAM")

echo
echo "Done → $OUT (chmod 600, docker-compose env_file format)."
echo "Deploy:  docker compose up -d"
echo "  (the proxy reads secrets.env via env_file and expands \${env:...} in the"
echo "   YAML itself — no envsubst / shell sourcing needed)."
