// SPDX-License-Identifier: GPL-3.0-only

//! Section-level admin config API (Wave 1 of the admin UI revamp).
//!
//! Provides section-scoped GET / PUT / validate endpoints:
//!
//! - `GET  /api/admin/config/section/:name[?format=yaml]`
//!   Returns the one named section (`admission` / `access` / `storage` /
//!   `advanced`) of the runtime config, with secrets redacted. JSON by
//!   default; `?format=yaml` emits the canonical YAML for that section only.
//! - `PUT  /api/admin/config/section/:name`
//!   Partial update: accepts JSON for the named section and replaces the
//!   corresponding slice of the in-memory [`Config`]. Routes through the
//!   shared [`super::apply_config_transition`] helper so field-level PATCH,
//!   document-level APPLY, and section-level PUT are all one transition
//!   story.
//! - `POST /api/admin/config/section/:name/validate`
//!   Dry-run variant: parses + validates the section body, computes the
//!   would-be diff, returns `{ok, warnings[], diff}`. No state change.
//!
//! The wire shape for each section is exactly the in-memory type in
//! [`crate::config_sections`] (`AdmissionSection`, `AccessSection`,
//! `StorageSection`, `AdvancedSection`) — so the UI's JSON schema is the
//! same one generated by `schemars` for the YAML view. One schema drives
//! both surfaces.
//!
//! ## Why this layer exists
//!
//! The UI revamp (`docs/plan/admin-ui-revamp.md` §6) needs a scope between
//! the existing *field-level* PATCH (which takes an ad-hoc flat JSON that
//! doesn't match the YAML document) and the *document-level* APPLY (which
//! requires the operator to ship a full canonical YAML even to edit one
//! toggle). The section API gives the UI a natural atomic unit — "apply
//! my Admission section edits, leave Access / Storage / Advanced alone" —
//! while keeping the same hot-reload + persist semantics as the full-
//! document path.

use axum::extract::{Path, Query, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

use super::super::{audit_log, AdminState};
use super::{active_config_path, apply_config_transition, unknown_section_error, SectionName};
use crate::config_sections::{AdmissionSection, SectionedConfig};

/// Query params for the section GET endpoint.
#[derive(Deserialize, Default)]
pub struct SectionGetQuery {
    /// `"yaml"` to return canonical YAML for this section. Omitted /
    /// anything else returns JSON.
    #[serde(default)]
    format: Option<String>,
}

/// Response body for section PUT + validate.
///
/// Mirrors [`super::ConfigValidateResponse`] in spirit but carries a diff
/// list — the UI renders this inside the plan → diff → apply dialog
/// described in the revamp plan §5.3.
#[derive(Serialize)]
pub struct SectionApplyResponse {
    /// `true` when the section was applied (PUT) or would apply cleanly
    /// (validate). `false` when validation rejected the body; the `error`
    /// field carries the reason.
    pub ok: bool,
    /// Human-readable warnings — same contract as the field-level PATCH:
    /// the HTTP status stays 200 and warnings narrate any partial / best-
    /// effort outcomes (invalid log_level, IAM-mode-gated legacy creds,
    /// etc.). Rendered in the Apply dialog above the confirm button.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub warnings: Vec<String>,
    /// `true` when at least one field in the transition is in the restart-
    /// required set (see [`apply_config_transition`]). The UI surfaces this
    /// as a banner in the Apply dialog so operators don't ship a
    /// restart-requiring change during a busy window without noticing.
    pub requires_restart: bool,
    /// Only set on PUT success — path the persisted YAML was written to.
    /// Absent for dry-run (validate) responses.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persisted_path: Option<String>,
    /// Machine-readable error string when `ok: false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// JSON Merge Patch showing what would change relative to the current
    /// runtime config, scoped to the submitted section. The UI renders it
    /// in the Apply dialog as a side-by-side diff (§5.3 of the plan).
    ///
    /// The structure is `{ section_name: { field_path: {before, after} } }`
    /// — a shallow per-field diff, not a full structural diff. That's
    /// enough for the UI's "cache_size_mb: 256 → 2048" view; deeper diffs
    /// (e.g. which bucket entry changed) are shown by the richer section
    /// editors directly, not by this endpoint.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub diff: Option<serde_json::Value>,
}

/// Build an early-return rejection response for the section endpoints.
/// Encodes the "always-pair a status code with a SectionApplyResponse
/// carrying an error message" pattern that repeated ~8× across
/// `get_section` + `apply_section` — the boilerplate now lives here
/// so handler bodies focus on what changed between failure cases.
///
/// `warnings` and `diff` default to empty/None, which fits most reject
/// sites; the handful of sites that want to carry validation warnings
/// or a precomputed diff through still build the response inline.
fn reject(status: StatusCode, error: impl Into<String>) -> Response {
    (
        status,
        Json(SectionApplyResponse {
            ok: false,
            warnings: vec![],
            requires_restart: false,
            persisted_path: None,
            error: Some(error.into()),
            diff: None,
        }),
    )
        .into_response()
}

/// `GET /api/admin/config/section/:name` — serialize the named slice of
/// the runtime config.
///
/// JSON by default (matches the shape the UI's form controllers expect).
/// `?format=yaml` emits the canonical YAML for that one section — useful
/// for the per-section Copy-as-YAML button described in §3.3 of the plan.
/// Secrets are redacted via the same [`Config::redact_all_secrets`] used
/// by the document-level export.
pub async fn get_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    Query(query): Query<SectionGetQuery>,
) -> impl IntoResponse {
    let Some(section) = SectionName::parse(&name) else {
        return reject(StatusCode::NOT_FOUND, unknown_section_error(&name));
    };

    let cfg = state.config.read().await;
    let redacted = cfg.redact_all_secrets();
    let sectioned = SectionedConfig::from_flat(&redacted);
    drop(cfg);

    let yaml_format = query.format.as_deref() == Some("yaml");

    match section {
        SectionName::Admission => emit_section(
            section,
            sectioned.admission.unwrap_or_default(),
            yaml_format,
        ),
        SectionName::Access => emit_section(section, sectioned.access, yaml_format),
        SectionName::Storage => emit_section(section, sectioned.storage, yaml_format),
        SectionName::Advanced => emit_section(section, sectioned.advanced, yaml_format),
    }
}

/// Serialize one section in the requested format. Factored out so
/// [`get_section`] stays one match arm per section — the generic makes
/// the format branch uniform.
fn emit_section<T: serde::Serialize>(
    section: SectionName,
    value: T,
    yaml_format: bool,
) -> axum::response::Response {
    if yaml_format {
        // Emit `<name>:\n  ...fields...` — matches the shape this same
        // block would take inside the full canonical YAML. The empty-
        // section case (e.g. `admission:` with no blocks) is normal
        // and not an error; the client renders an editor seeded with
        // the section's defaults.
        let mut map = serde_yaml::Mapping::new();
        let value_yaml = match serde_yaml::to_value(&value) {
            Ok(v) => v,
            Err(e) => {
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("failed to serialize section to YAML: {}", e),
                )
                    .into_response();
            }
        };
        map.insert(
            serde_yaml::Value::String(section.as_str().to_string()),
            value_yaml,
        );
        let doc = serde_yaml::Value::Mapping(map);
        match serde_yaml::to_string(&doc) {
            Ok(s) => (
                StatusCode::OK,
                [(axum::http::header::CONTENT_TYPE, "application/yaml")],
                s,
            )
                .into_response(),
            Err(e) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("failed to serialize section to YAML: {}", e),
            )
                .into_response(),
        }
    } else {
        (StatusCode::OK, Json(value)).into_response()
    }
}

/// `PUT /api/admin/config/section/:name` — apply a section partial.
///
/// Body is JSON matching the target section's shape (the same type used
/// by the YAML serializer — no ad-hoc wrapper). The section replaces its
/// slice in the in-memory `SectionedConfig`; the rest of the document
/// stays intact. Transition happens under a single write lock:
///
/// 1. Clone the current `Config` into a prospective `new_cfg`.
/// 2. Deserialize the body into the target section struct.
/// 3. Replace the one field on a `SectionedConfig::from_flat(&new_cfg)`.
/// 4. `into_flat()` to collapse back (runs the same `normalize` + admission
///    validation as the YAML path).
/// 5. Preserve runtime secrets across the section (exporting redacts, so
///    a round-trip put would otherwise clear creds).
/// 6. Hand off to [`apply_config_transition`] for hot-reload side effects.
/// 7. Persist atomically.
///
/// The result's `diff` field shows exactly what changed relative to the
/// pre-PUT state so the Apply dialog can display it.
pub async fn put_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    headers: HeaderMap,
    body: Json<serde_json::Value>,
) -> impl IntoResponse {
    apply_section(
        state,
        name,
        body.0,
        ApplyMode::PersistAndApply,
        Some(headers),
    )
    .await
}

/// `POST /api/admin/config/section/:name/validate` — dry-run a section apply.
///
/// Same inputs as PUT, but no state change and no persist. Returns
/// `ok`, the computed diff, and warnings. The UI calls this when the
/// operator presses Apply: the diff is rendered in the confirmation
/// modal (§5.3), and a second click on "Apply and Persist" fires the
/// real PUT. Keeping validate in the same module as PUT makes the
/// "validate-then-apply" contract structurally obvious.
pub async fn validate_section(
    State(state): State<Arc<AdminState>>,
    Path(name): Path<String>,
    body: Json<serde_json::Value>,
) -> impl IntoResponse {
    apply_section(state, name, body.0, ApplyMode::DryRun, None).await
}

/// Whether a section operation should mutate + persist, or only report
/// the would-be result.
enum ApplyMode {
    DryRun,
    PersistAndApply,
}

/// Shared implementation of PUT + validate. The only difference is
/// whether to mutate state and persist at the end — every parse,
/// validate, diff, and transition step runs identically so the two
/// surfaces can't drift.
async fn apply_section(
    state: Arc<AdminState>,
    name: String,
    body: serde_json::Value,
    mode: ApplyMode,
    headers: Option<HeaderMap>,
) -> axum::response::Response {
    let Some(section) = SectionName::parse(&name) else {
        return reject(StatusCode::NOT_FOUND, unknown_section_error(&name));
    };

    // Take the write lock once for the whole transition — the same
    // lock-scope discipline as `apply_config_doc`, so a racing PATCH
    // can't sneak between our compare and swap.
    let mut cfg = state.config.write().await;
    let old_cfg = cfg.clone();

    // Project current config → sectioned shape → replace one slice →
    // collapse back. The replacement does NOT touch secrets on the
    // current config (we merge them back after); the operator's body
    // is treated as "the new non-secret state of this section".
    let mut sectioned = SectionedConfig::from_flat(&old_cfg);
    if let Err(err) = merge_patch_section(&mut sectioned, section, &body) {
        return reject(StatusCode::BAD_REQUEST, err);
    }

    // Collapse back to flat. This runs the same `storage.normalize()`
    // and `AdmissionSpec::validate()` the YAML loader runs — structural
    // errors in the body surface here with the same messages the YAML
    // view would show.
    let mut new_cfg = match sectioned.into_flat() {
        Ok(c) => c,
        Err(err) => return reject(StatusCode::BAD_REQUEST, err),
    };

    // Defense-in-depth: refuse explicit bootstrap_password_hash
    // changes through the section API, mirroring the document-level
    // `apply_config_doc` guard (cfg.rs `document_level.rs:463-476`).
    // The legitimate path is `PUT /api/admin/password`, which
    // verifies the current password and re-encrypts the config DB
    // atomically. Accepting an arbitrary hash here would let an
    // admin-session holder lock future admins out of the GUI.
    //
    // MUST run BEFORE the unconditional `new_cfg.bootstrap_password_hash
    // = old_cfg...` overwrite below — otherwise an attacker-supplied
    // hash would be silently clobbered by the overwrite and the
    // security model's contract would depend on an implementation
    // detail (the ordering) rather than an explicit check.
    if new_cfg.bootstrap_password_hash != old_cfg.bootstrap_password_hash {
        return reject(
            StatusCode::FORBIDDEN,
            "bootstrap_password_hash cannot be changed via /config/section; use PUT /api/admin/password (verifies the current password and re-encrypts the config DB atomically)",
        );
    }

    // Preserve runtime secrets across the section edit. The GET
    // surfaces (export, section GET) redact every secret; a naïve
    // round-trip (GET → edit → PUT) would therefore post None for
    // every creds pair. We mirror the document-level apply's
    // "preserve when None on the incoming side" semantics so section
    // round-trips don't silently clear authentication state.
    //
    // Infra secrets — preservation rules differ:
    //
    // bootstrap_password_hash: ALWAYS preserved via this path. It
    // has its own dedicated rotation endpoint (PUT /api/admin/password)
    // that verifies the current password and re-encrypts the config
    // DB atomically. The explicit equality guard above ensures we
    // only reach this line when incoming == old, so this is
    // effectively a defensive no-op for that field.
    new_cfg.bootstrap_password_hash = old_cfg.bootstrap_password_hash.clone();

    // STEP-1: cred preservation. Uses the SAME shared helpers as
    // `apply_config_doc` (see `super::preserve_sigv4_pair`,
    // `preserve_primary_backend_creds`, `preserve_named_backends_creds`
    // in `mod.rs`). Both write paths MUST stay in lockstep on the
    // contract: redaction-round-trip safe, asymmetric SigV4 refuses
    // to cross-wire (warns instead), backend type-flips and
    // rename/removed-backends emit warnings.
    //
    // The encryption-key three-state semantics for the singleton +
    // per-backend `encryption` fields run separately below (Step 6)
    // because they need the raw JSON body to distinguish "absent"
    // from "explicit null" — that distinction is lost after the
    // merge-patch + collapse.
    let mut cred_warnings: Vec<String> = Vec::new();
    super::preserve_sigv4_pair(
        &mut new_cfg.access_key_id,
        &mut new_cfg.secret_access_key,
        &old_cfg.access_key_id,
        &old_cfg.secret_access_key,
        "proxy-level",
        &mut cred_warnings,
    );
    super::preserve_primary_backend_creds(&mut new_cfg, &old_cfg, &mut cred_warnings);
    super::preserve_named_backends_creds(&mut new_cfg, &old_cfg, &mut cred_warnings);

    // Step 6: per-backend encryption key preservation. Three-state
    // semantics PER FIELD PER ENTRY:
    //   * key field absent in body  → preserve old key (default
    //     GET→edit→PUT round-trip safety).
    //   * key field present and null → explicit clear (operator
    //     clicked "Disable encryption" on this backend).
    //   * key field present and string → validate hex + rotate.
    //
    // Same three-state logic applies to `legacy_key` on each mode.
    //
    // We walk the RAW body JSON to distinguish absent from null;
    // after merge-patch the two both deserialise to None. The
    // sectioned body shape places this at
    // `storage.backend_encryption.key` and
    // `storage.backends[i].encryption.key` (matched by backend
    // name, not by list index — operators may reorder the list).
    let body_probe = BackendEncryptionKeyProbe::from_section(section, &body);
    preserve_backend_encryption_secrets(
        &mut new_cfg.backend_encryption,
        &old_cfg.backend_encryption,
        body_probe.for_singleton(),
    );
    for new_named in &mut new_cfg.backends {
        if let Some(old_named) = old_cfg.backends.iter().find(|n| n.name == new_named.name) {
            let probe = body_probe.for_named(&new_named.name);
            preserve_backend_encryption_secrets(
                &mut new_named.encryption,
                &old_named.encryption,
                probe,
            );
        }
    }

    // Webhook header values are masked to REDACTED_SENTINEL on GET; restore any
    // the operator left untouched so an unedited round-trip doesn't clobber the
    // real bearer token. (Headers the operator retyped or removed pass through.)
    super::preserve_event_delivery_secrets(&mut new_cfg.event_delivery, &old_cfg.event_delivery);

    // The `removed_warnings` name is preserved here for readability of the
    // downstream call sites that thread it into `SectionApplyResponse`.
    // It now carries the FULL cred-preservation warning bag
    // (asymmetric SigV4, type-flips, renamed/removed backends) emitted
    // by the shared helpers above — same warning surface the
    // document-level apply path produces for equivalent edits.
    let removed_warnings = cred_warnings;

    // Y1: normalise shorthand forms (bucket `public: true`, storage
    // `s3:`/`filesystem:` — anything `Config::normalize_shorthands`
    // covers). The YAML loader runs this right after from_yaml_str;
    // the section PUT needs the same pass so a `public: true`
    // shorthand actually expands to `public_prefixes: [""]` before
    // `rebuild_bucket_derived_snapshots` walks the buckets.
    if let Err(e) = new_cfg.normalize_shorthands() {
        return (
            StatusCode::BAD_REQUEST,
            Json(SectionApplyResponse {
                ok: false,
                warnings: removed_warnings,
                requires_restart: false,
                persisted_path: None,
                error: Some(format!("{}", e)),
                diff: None,
            }),
        )
            .into_response();
    }

    // Validate semantically via `Config::check` (runs the same
    // warnings pipeline the document-level apply runs).
    let warnings_from_check = new_cfg.check();

    // Compute the diff before we potentially swap. This is the shape
    // the UI renders in the Apply dialog.
    let diff = compute_section_diff(section, &old_cfg, &new_cfg);

    // Compute `requires_restart` from the old vs. new config directly
    // (no state mutation). The same fields
    // [`apply_config_transition`] checks — `listen_addr`,
    // `cache_size_mb` — are compared here without touching the
    // runtime. Dry-run stays stateless.
    let requires_restart = restart_required_between(&old_cfg, &new_cfg);

    // Dry-run: no state mutation, no engine rebuild. The apply dialog
    // gets the diff + warnings_from_check + restart-required flag so
    // the operator can review before confirming. Engine-rebuild
    // failures (e.g. bad S3 endpoint) are only surfaced on the real
    // PUT — the risk of making dry-run briefly flip the runtime to
    // the proposed state (which admission_chain / engine / iam_state
    // are all ArcSwap-observed, i.e. concurrent request-serving code
    // can see the flip) is not worth catching engine errors earlier
    // than they happen in PUT anyway.
    if matches!(mode, ApplyMode::DryRun) {
        // Declarative-IAM preview: when the target mode would be
        // Declarative AND the IAM fields have changed, compute the
        // would-be reconcile diff (validation-only, zero DB writes)
        // and surface the summary line in warnings so the Apply
        // dialog shows what the live apply would actually do. This
        // is the same `diff_iam` the live apply uses, so the preview
        // can't lie.
        let mut preview_warnings: Vec<String> = Vec::new();
        if matches!(
            new_cfg.iam_mode,
            crate::config_sections::IamMode::Declarative
        ) {
            let old_iam_unchanged = matches!(
                old_cfg.iam_mode,
                crate::config_sections::IamMode::Declarative
            ) && old_cfg.iam_users == new_cfg.iam_users
                && old_cfg.iam_groups == new_cfg.iam_groups
                && old_cfg.auth_providers == new_cfg.auth_providers
                && old_cfg.group_mapping_rules == new_cfg.group_mapping_rules;

            if !old_iam_unchanged {
                let yaml_snapshot = crate::iam::snapshot_from_access(
                    &new_cfg.iam_users,
                    &new_cfg.iam_groups,
                    &new_cfg.auth_providers,
                    &new_cfg.group_mapping_rules,
                );
                // Empty-gate preview: the live apply would refuse
                // this, so surface it at dry-run time too.
                if matches!(old_cfg.iam_mode, crate::config_sections::IamMode::Gui)
                    && yaml_snapshot.is_empty()
                {
                    preview_warnings.push(
                        "declarative IAM preview: flip to declarative mode with empty iam_users / \
                         iam_groups would be REFUSED by the live apply (would wipe the DB). \
                         Add IAM content to the YAML first."
                            .to_string(),
                    );
                } else if let Some(db_arc) = state.config_db.as_ref() {
                    let db = db_arc.lock().await;
                    match crate::iam::preview_declarative_iam(&db, &yaml_snapshot) {
                        Ok(iam_diff) if iam_diff.is_empty() => {
                            preview_warnings.push(
                                "declarative IAM preview: no IAM changes (idempotent apply)"
                                    .to_string(),
                            );
                        }
                        Ok(iam_diff) => {
                            preview_warnings.push(format!(
                                "declarative IAM preview: {}",
                                iam_diff.summary_line()
                            ));
                        }
                        Err(e) => {
                            preview_warnings.push(format!(
                                "declarative IAM preview REJECTED at validation (live apply \
                                 would return this error verbatim): {}",
                                e
                            ));
                        }
                    }
                }
            }
        }

        return (
            StatusCode::OK,
            Json(SectionApplyResponse {
                ok: true,
                warnings: removed_warnings
                    .clone()
                    .into_iter()
                    .chain(warnings_from_check)
                    .chain(preview_warnings)
                    .collect(),
                requires_restart,
                persisted_path: None,
                error: None,
                diff: Some(diff),
            }),
        )
            .into_response();
    }

    // PersistAndApply: run the full transition (engine rebuild + log
    // reload + IAM swap + snapshot rebuilds). On failure we return
    // UNPROCESSABLE_ENTITY — caller fixes and re-applies.
    let (transition_warnings, transition_restart) =
        match apply_config_transition(&state, &old_cfg, &new_cfg).await {
            Ok(pair) => pair,
            Err(e) => {
                return (
                    StatusCode::UNPROCESSABLE_ENTITY,
                    Json(SectionApplyResponse {
                        ok: false,
                        warnings: removed_warnings
                            .into_iter()
                            .chain(warnings_from_check)
                            .collect(),
                        requires_restart: false,
                        persisted_path: None,
                        error: Some(format!(
                            "Failed to apply section '{}' (no state changed): {}",
                            section.as_str(),
                            e
                        )),
                        diff: Some(diff),
                    }),
                )
                    .into_response();
            }
        };

    // Transition's `requires_restart` is authoritative for the PUT
    // response (it's the same value the field-level PATCH and
    // document-level APPLY return). Our earlier `requires_restart`
    // from `restart_required_between` was only for the dry-run path;
    // it should match what the transition just returned but we always
    // defer to the transition's computation here.
    debug_assert_eq!(
        requires_restart, transition_restart,
        "dry-run's restart_required_between must agree with apply_config_transition"
    );
    let requires_restart = transition_restart;

    // Swap the config in memory and persist.
    *cfg = new_cfg;

    let persist_path = active_config_path(&state);
    // The `persisted: bool` is folded into `status` + `persist_warning`
    // below — we don't expose it separately on `SectionApplyResponse` the
    // way the document-level `ConfigApplyResponse` does. Callers infer
    // the persist outcome from the HTTP status (200 vs. 500) and the
    // warning text if any.
    let (persisted_path, status, persist_warning) = match cfg.persist_to_file(&persist_path) {
        Ok(()) => (Some(persist_path.clone()), StatusCode::OK, None),
        Err(e) => (
            None,
            StatusCode::INTERNAL_SERVER_ERROR,
            Some(format!(
                "Applied section '{}' in memory but FAILED to persist to {}: {}. Server will revert on next restart — fix the IO and re-apply.",
                section.as_str(),
                persist_path,
                e
            )),
        ),
    };

    if let Some(h) = headers {
        audit_log(
            &format!("apply_config_section:{}", section.as_str()),
            "admin",
            &persist_path,
            &h,
        );
    }

    let warnings: Vec<String> = removed_warnings
        .into_iter()
        .chain(warnings_from_check)
        .chain(transition_warnings)
        .chain(persist_warning)
        .collect();

    (
        status,
        Json(SectionApplyResponse {
            ok: true,
            warnings,
            requires_restart,
            persisted_path,
            error: None,
            diff: Some(diff),
        }),
    )
        .into_response()
}

/// Apply a JSON-Merge-Patch (RFC 7396) body on top of one section of
/// a `SectionedConfig`.
///
/// ## Why merge, not replace
///
/// A naïve "replace the whole section" semantic is a serious foot-gun
/// for the UI's section PUT: the operator edits one field in the
/// admin form (say, `advanced.max_delta_ratio`), the client sends
/// `{max_delta_ratio: 0.42}`, and the server silently resets every
/// OTHER advanced field to its compile-time default because they
/// were absent from the body. We observed this live in local browser
/// testing against v0.8.0 — one edit zeroed `cache_size_mb`,
/// `listen_addr`, and `log_level`.
///
/// RFC 7396 JSON Merge Patch is the right semantic for partial
/// updates:
///   * Keys present in body -> apply (replace-in-place at that key).
///   * Keys absent from body -> keep the old value.
///   * Keys set to `null` in body -> delete / fall back to default.
///
/// List-valued fields like `admission.blocks` are atomic leaves
/// (present-or-absent, no per-index merge); sending `{blocks: []}`
/// clears the chain. Map-valued fields like `storage.buckets` are
/// merged entry-by-entry (per-bucket null deletes that bucket,
/// other buckets stay untouched).
///
/// ## Implementation
///
/// Each arm projects the current section to JSON via
/// [`merge_into_typed`], applies the merge patch, and deserializes
/// back. Structural errors (unknown fields, bad types) surface
/// through serde the same way they would with replace semantics.
/// The match is exhaustive on [`SectionName`] so adding a fifth
/// section breaks this file noisily until every branch is updated.
fn merge_patch_section(
    sectioned: &mut SectionedConfig,
    section: SectionName,
    body: &serde_json::Value,
) -> Result<(), String> {
    match section {
        SectionName::Admission => {
            // Admission's `Option<AdmissionSection>` lives in the
            // sectioned shape, but at merge time we project the inner
            // `AdmissionSection` (default when `None`). After merge,
            // collapse back to `None` when blocks are empty so the
            // emitted YAML stays minimal.
            let current = sectioned.admission.clone().unwrap_or_default();
            let merged: AdmissionSection = merge_into_typed(&current, body, "admission")?;
            sectioned.admission = if merged.blocks.is_empty() {
                None
            } else {
                Some(merged)
            };
        }
        SectionName::Access => {
            sectioned.access = merge_into_typed(&sectioned.access, body, "access")?;
        }
        SectionName::Storage => {
            sectioned.storage = merge_into_typed(&sectioned.storage, body, "storage")?;
        }
        SectionName::Advanced => {
            sectioned.advanced = merge_into_typed(&sectioned.advanced, body, "advanced")?;
        }
    }
    Ok(())
}

/// Merge a JSON patch onto a typed section value and re-deserialize.
///
/// `current` is projected to JSON, the patch is applied in-place per
/// RFC 7396, and the result is parsed back into `T`. Error messages
/// are scoped by `label` (`"admission"`, `"access"`, …) so the
/// serde diagnostic the operator sees names the right section.
///
/// The generic bound is `Serialize + DeserializeOwned` and nothing
/// else; every section type in [`crate::config_sections`] satisfies
/// it. Keeps the four arms of [`merge_patch_section`] free of copy-
/// paste — mutating a section now means adding one line, not five.
fn merge_into_typed<T>(
    current: &T,
    patch: &serde_json::Value,
    label: &'static str,
) -> Result<T, String>
where
    T: serde::Serialize + serde::de::DeserializeOwned,
{
    let mut merged = serde_json::to_value(current)
        .map_err(|e| format!("internal: failed to project {} section: {}", label, e))?;
    apply_merge_patch(&mut merged, patch);
    serde_json::from_value(merged).map_err(|e| format!("invalid {} section body: {}", label, e))
}

/// Apply a JSON Merge Patch (RFC 7396) in-place to `target`.
///
/// The algorithm is short enough to inline rather than pull in an
/// external crate:
///
///   * If `patch` is an object and `target` is an object, recurse
///     into each patch key:
///       - patch[k] == null -> remove k from target
///       - patch[k] == anything else -> recursively merge into target[k]
///       - if target[k] is absent, target[k] = patch[k].clone()
///   * Otherwise `patch` replaces `target` wholesale.
///
/// This is the standard spec; arrays are replaced atomically.
fn apply_merge_patch(target: &mut serde_json::Value, patch: &serde_json::Value) {
    match (target, patch) {
        (serde_json::Value::Object(target_map), serde_json::Value::Object(patch_map)) => {
            for (k, v) in patch_map {
                if v.is_null() {
                    target_map.remove(k);
                } else {
                    match target_map.get_mut(k) {
                        Some(existing) => apply_merge_patch(existing, v),
                        None => {
                            target_map.insert(k.clone(), v.clone());
                        }
                    }
                }
            }
        }
        (target_slot, _) => {
            *target_slot = patch.clone();
        }
    }
}

/// Compute the per-field diff for one section.
///
/// Semantics: project both configs into a `SectionedConfig`, pick the
/// named section off each, run a shallow recursive diff on the two
/// JSON representations, and return
/// `{ "<section>": { "<path>": {"before": ..., "after": ...} } }`.
///
/// The diff intentionally collapses equal values — the UI only wants to
/// render what changed. For Admission, the blocks list is diffed by
/// name so reorders surface as a single pair of before/after lists
/// rather than N spurious per-index changes. (Other sections are
/// scalar-heavy so per-field is enough.)
/// Map a secret's plaintext to a deterministic, non-reversible
/// placeholder suitable for the Apply-dialog diff. Preserved secrets
/// compare equal (same fingerprint); rotations show a readable
/// swap (`fp:abc12345…` → `fp:def67890…`) without leaking material.
///
/// Used for per-backend encryption `key` and `legacy_key` on the
/// storage section diff (see `inject_encryption_fingerprints`). The
/// SigV4 pair and backend creds are handled by `redact_all_secrets`
/// which nulls them — they don't rotate through this endpoint.
///
/// 8-hex-char truncation is enough to distinguish rotations
/// practically; the full SHA-256 is needlessly long in the UI.
fn fingerprint_secret(plaintext: Option<&str>) -> Option<String> {
    plaintext.map(|pt| {
        use sha2::{Digest, Sha256};
        let digest = Sha256::digest(pt.as_bytes());
        format!("fp:{}", hex::encode(&digest[..4]))
    })
}

fn compute_section_diff(
    section: SectionName,
    old_cfg: &crate::config::Config,
    new_cfg: &crate::config::Config,
) -> serde_json::Value {
    // Redact BOTH sides. If only one side is redacted the diff
    // spuriously "changes" a preserved credential to a placeholder
    // (or vice versa) and the client surfaces it in the Apply
    // dialog — operators would see "password changed" on a plain
    // `advanced.max_delta_ratio` edit. Redacting both means secrets
    // either compare-equal (preserved) or both appear as the same
    // redaction placeholder.
    //
    // Per-backend encryption keys (primary + legacy shim) need
    // special handling: `redact_all_secrets` nulls them on BOTH
    // sides, which hides real rotations. We fingerprint them
    // instead — each plaintext maps to a deterministic-but-non-
    // reversible `fp:xxxxxxxx` placeholder so:
    //   * unchanged keys compare equal (no spurious diff).
    //   * rotations surface as a readable `fp:a→fp:b` swap.
    //   * neither side leaks key material (one-way hash truncated
    //     to 8 hex chars, matching the pre-refactor behaviour).
    let old_redacted = old_cfg.redact_all_secrets();
    let new_redacted = new_cfg.redact_all_secrets();

    let old_sectioned = SectionedConfig::from_flat(&old_redacted);
    let new_sectioned = SectionedConfig::from_flat(&new_redacted);

    let (mut old_json, mut new_json) = match section {
        SectionName::Admission => (
            serde_json::to_value(old_sectioned.admission.unwrap_or_default()).unwrap_or_default(),
            serde_json::to_value(new_sectioned.admission.unwrap_or_default()).unwrap_or_default(),
        ),
        SectionName::Access => (
            serde_json::to_value(old_sectioned.access).unwrap_or_default(),
            serde_json::to_value(new_sectioned.access).unwrap_or_default(),
        ),
        SectionName::Storage => (
            serde_json::to_value(old_sectioned.storage).unwrap_or_default(),
            serde_json::to_value(new_sectioned.storage).unwrap_or_default(),
        ),
        SectionName::Advanced => (
            serde_json::to_value(old_sectioned.advanced).unwrap_or_default(),
            serde_json::to_value(new_sectioned.advanced).unwrap_or_default(),
        ),
    };

    // Storage section gets the per-backend encryption fingerprint
    // injection. Other sections have no encryption fields.
    if matches!(section, SectionName::Storage) {
        inject_encryption_fingerprints(
            &mut old_json,
            &old_cfg.backend_encryption,
            &old_cfg.backends,
        );
        inject_encryption_fingerprints(
            &mut new_json,
            &new_cfg.backend_encryption,
            &new_cfg.backends,
        );
    }

    let mut diff = serde_json::Map::new();
    shallow_diff("", &old_json, &new_json, &mut diff);

    let mut out = serde_json::Map::new();
    out.insert(
        section.as_str().to_string(),
        serde_json::Value::Object(diff),
    );
    serde_json::Value::Object(out)
}

/// Replace the nulled-by-redaction `key` / `legacy_key` fields in a
/// `storage`-section JSON value with fingerprints derived from the
/// real keys on the Config. Preserves the non-secret id fields
/// (key_id, kms_key_id) as-is.
fn inject_encryption_fingerprints(
    storage_json: &mut serde_json::Value,
    singleton_enc: &crate::config::BackendEncryptionConfig,
    named_backends: &[crate::config::NamedBackendConfig],
) {
    let obj = match storage_json.as_object_mut() {
        Some(m) => m,
        None => return,
    };
    // Singleton.
    if let Some(be) = obj.get_mut("backend_encryption") {
        apply_fingerprints_to_enc_json(be, singleton_enc);
    }
    // List.
    if let Some(arr) = obj.get_mut("backends").and_then(|v| v.as_array_mut()) {
        for entry in arr {
            let name = entry
                .get("name")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string());
            if let Some(n) = name {
                if let Some(enc_json) = entry.get_mut("encryption") {
                    if let Some(named) = named_backends.iter().find(|nb| nb.name == n) {
                        apply_fingerprints_to_enc_json(enc_json, &named.encryption);
                    }
                }
            }
        }
    }
}

/// Overwrite `key` / `legacy_key` fields on a single encryption JSON
/// object with fingerprints derived from the source config variant.
/// No-op when the source config has no key material (fingerprint
/// stays as the redacted null).
fn apply_fingerprints_to_enc_json(
    enc_json: &mut serde_json::Value,
    enc: &crate::config::BackendEncryptionConfig,
) {
    let obj = match enc_json.as_object_mut() {
        Some(m) => m,
        None => return,
    };
    if let Some(fp) = fingerprint_secret(enc.primary_key()) {
        obj.insert("key".to_string(), serde_json::Value::String(fp));
    }
    if let Some(fp) = fingerprint_secret(enc.legacy_key()) {
        obj.insert("legacy_key".to_string(), serde_json::Value::String(fp));
    }
}

/// What the operator said about each encryption key field for one
/// backend. Derived from the raw PUT body's JSON shape so the
/// merge-patch "absent vs null" distinction survives into the
/// preservation pass.
///
/// Both flags are independent — a PATCH that sets `key: null` and
/// leaves `legacy_key` absent clears the primary but preserves the
/// old shim. Vice versa for restoring a shim without rotating the
/// primary.
#[derive(Debug, Default, Clone, Copy)]
pub(crate) struct BackendKeyPresence {
    pub key_is_explicit_null: bool,
    pub legacy_key_is_explicit_null: bool,
}

/// Inspects a section-PUT body and reports, per backend-encryption
/// entry, whether each of `key` / `legacy_key` is present-as-null in
/// the raw JSON. After merge-patch these both collapse to None on
/// the flat `Config`; the probe recovers the distinction so
/// preservation can correctly distinguish "preserve" from
/// "explicitly clear".
pub(crate) struct BackendEncryptionKeyProbe {
    singleton: BackendKeyPresence,
    /// Per-backend-name probe results. `HashMap` keyed by backend
    /// name — matches the way preserve_backend_encryption_secrets
    /// walks the list.
    named: std::collections::HashMap<String, BackendKeyPresence>,
}

impl BackendEncryptionKeyProbe {
    /// Probe the raw section body. Only the `Storage` section carries
    /// encryption fields; others return empty probes (no-op preservation
    /// rules).
    pub(crate) fn from_section(section: SectionName, body: &serde_json::Value) -> Self {
        let mut singleton = BackendKeyPresence::default();
        let mut named: std::collections::HashMap<String, BackendKeyPresence> =
            std::collections::HashMap::new();
        if matches!(section, SectionName::Storage) {
            if let Some(obj) = body.as_object() {
                // Singleton: storage.backend_encryption
                if let Some(be) = obj.get("backend_encryption") {
                    singleton = probe_enc_body(be);
                }
                // List: storage.backends[] — each with a `name` and
                // optional `encryption` object.
                if let Some(arr) = obj.get("backends").and_then(|v| v.as_array()) {
                    for entry in arr {
                        if let Some(name) = entry
                            .get("name")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string())
                        {
                            if let Some(enc) = entry.get("encryption") {
                                named.insert(name, probe_enc_body(enc));
                            }
                        }
                    }
                }
            }
        }
        Self { singleton, named }
    }

    pub(crate) fn for_singleton(&self) -> BackendKeyPresence {
        self.singleton
    }

    pub(crate) fn for_named(&self, name: &str) -> BackendKeyPresence {
        self.named.get(name).copied().unwrap_or_default()
    }
}

/// Probe a single `encryption: {...}` object for explicit-null key
/// fields. Missing object → both flags false (preservation default).
fn probe_enc_body(enc: &serde_json::Value) -> BackendKeyPresence {
    let obj = match enc.as_object() {
        Some(m) => m,
        None => return BackendKeyPresence::default(),
    };
    BackendKeyPresence {
        key_is_explicit_null: obj.get("key").map(|v| v.is_null()).unwrap_or(false),
        legacy_key_is_explicit_null: obj.get("legacy_key").map(|v| v.is_null()).unwrap_or(false),
    }
}

/// Preserve encryption key material on a single backend entry
/// across a section PUT.
///
/// Semantics for each of `key` / `legacy_key`:
///   * body absent, new==None → restore from old (preserve).
///   * body null, new==None → leave None (explicit clear).
///   * new==Some → operator rotated; validate hex, keep as-is.
///
/// No-op on variants that don't carry the field (e.g. SseS3 has no
/// primary `key`).
fn preserve_backend_encryption_secrets(
    new: &mut crate::config::BackendEncryptionConfig,
    old: &crate::config::BackendEncryptionConfig,
    probe: BackendKeyPresence,
) {
    use crate::config::BackendEncryptionConfig as E;
    // H8: validate hex during preservation. If the old config landed
    // in memory with malformed hex (e.g. a pre-existing pathological
    // state from a prior load that only warned, not errored), DON'T
    // propagate that into the new config — the subsequent
    // `rebuild_engine → wrap_backend_with_encryption →
    // EncryptionKey::from_hex` would 5xx on a PATCH that touched an
    // unrelated field. Silently skip preservation for unparseable
    // old keys; the engine's warn-level "no key configured" diagnostic
    // will surface the underlying issue.
    let old_primary_ok = old
        .primary_key()
        .filter(|k| crate::storage::EncryptionKey::from_hex(k).is_ok())
        .map(str::to_string);
    let old_legacy_ok = old
        .legacy_key()
        .filter(|k| crate::storage::EncryptionKey::from_hex(k).is_ok())
        .map(str::to_string);

    // Primary key preservation — only relevant on Aes256GcmProxy.
    // Same-mode, absent-in-body ⇒ preserve old primary.
    if let E::Aes256GcmProxy {
        key: ref mut new_key,
        ..
    } = new
    {
        if new_key.is_none() && !probe.key_is_explicit_null {
            if let Some(old_key) = &old_primary_ok {
                *new_key = Some(old_key.clone());
            }
        }
    }

    // Mode-flip auto-promotion (correctness x-ray C3):
    // When the operator changes mode AWAY from Aes256GcmProxy (the
    // only mode with a primary key), auto-promote the old primary
    // key + derived id into the new config's legacy_key slot IFF
    // the operator didn't explicitly set legacy_key on the new
    // config. This preserves historical-read capability — without
    // this, a mode flip through the admin UI (which redacts the
    // primary key on GET) silently orphans every historical object:
    // the next read returns "object encrypted, no key configured".
    //
    // The operator can still OVERRIDE this by explicitly passing
    // `legacy_key: null` in the body — that's the "discard old keys"
    // escape hatch, encoded via `probe.legacy_key_is_explicit_null`.
    let mode_changed_from_proxy =
        matches!(old, E::Aes256GcmProxy { .. }) && !matches!(new, E::Aes256GcmProxy { .. });
    if mode_changed_from_proxy && !probe.legacy_key_is_explicit_null {
        // Only auto-populate if the new legacy_key slot is empty AND
        // the old primary has a VALIDATED key (`old_primary_ok`). A
        // redact-round-trip yields None → no-op; a pre-existing
        // malformed hex yields None via the H8 validation → no-op.
        if let (Some(old_primary), Some(new_legacy_slot)) = (&old_primary_ok, new.legacy_key_mut())
        {
            if new_legacy_slot.is_none() {
                *new_legacy_slot = Some(old_primary.clone());
            }
        }
    }

    // Legacy shim key preservation — same-slot absent-in-body.
    // Runs AFTER the auto-promotion so explicit operator intent
    // (a fresh legacy_key in the body) always wins over the
    // promoted value. Uses the H8-validated variable so malformed
    // hex doesn't propagate.
    if let Some(new_legacy) = new.legacy_key_mut() {
        if new_legacy.is_none() && !probe.legacy_key_is_explicit_null {
            *new_legacy = old_legacy_ok;
        }
    }
}

/// Non-mutating predicate: would applying `new` on top of `old` require
/// a server restart to take effect?
///
/// Delegates to [`super::requires_restart_warnings`] so the section-
/// level dry-run and the runtime [`apply_config_transition`] cannot
/// drift on what counts as restart-required. Keeping this wrapper
/// named `restart_required_between` preserves the local call sites'
/// predicate shape (`bool`, not `Vec<String>`) — the dry-run doesn't
/// care about the per-field warning text, only whether ANY field
/// needs a restart.
fn restart_required_between(old: &crate::config::Config, new: &crate::config::Config) -> bool {
    !super::requires_restart_warnings(old, new).is_empty()
}

/// Recursively diff two JSON values. Leaves surface as
/// `{before, after}` pairs keyed by dotted path. Arrays are treated
/// as opaque leaves (either equal or both surfaces); that's sufficient
/// for the UI's "what changed" summary without introducing list-diff
/// complexity here.
fn shallow_diff(
    prefix: &str,
    old: &serde_json::Value,
    new: &serde_json::Value,
    out: &mut serde_json::Map<String, serde_json::Value>,
) {
    match (old, new) {
        (serde_json::Value::Object(o), serde_json::Value::Object(n)) => {
            let mut keys: std::collections::BTreeSet<&String> = o.keys().collect();
            keys.extend(n.keys());
            for k in keys {
                let child_prefix = if prefix.is_empty() {
                    k.clone()
                } else {
                    format!("{}.{}", prefix, k)
                };
                let ov = o.get(k).unwrap_or(&serde_json::Value::Null);
                let nv = n.get(k).unwrap_or(&serde_json::Value::Null);
                shallow_diff(&child_prefix, ov, nv, out);
            }
        }
        _ => {
            if old != new {
                let mut pair = serde_json::Map::new();
                pair.insert("before".to_string(), old.clone());
                pair.insert("after".to_string(), new.clone());
                out.insert(prefix.to_string(), serde_json::Value::Object(pair));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::BackendEncryptionConfig as E;

    const HEX32: &str = "0101010101010101010101010101010101010101010101010101010101010101";
    const HEX32_B: &str = "0202020202020202020202020202020202020202020202020202020202020202";

    fn proxy(key: Option<&str>, legacy: Option<&str>) -> E {
        E::Aes256GcmProxy {
            key: key.map(str::to_string),
            key_id: None,
            legacy_key: legacy.map(str::to_string),
            legacy_key_id: None,
        }
    }

    fn kms(legacy: Option<&str>) -> E {
        E::SseKms {
            kms_key_id: "arn:aws:kms:us-east-1:123:key/abc".into(),
            bucket_key_enabled: true,
            legacy_key: legacy.map(str::to_string),
            legacy_key_id: None,
        }
    }

    #[test]
    fn preserve_mode_flip_proxy_to_kms_auto_promotes_primary_to_legacy() {
        // Regression for correctness x-ray C3: operator edits the
        // storage section with the UI, which redacts the primary key
        // on GET. Body says `{mode: sse-kms, kms_key_id: ...}` — no
        // legacy_key. Before the fix, the old primary key silently
        // disappeared and every historical object on the backend
        // became unreadable.
        let old = proxy(Some(HEX32), None);
        let mut new = kms(None);
        let probe = BackendKeyPresence::default();
        preserve_backend_encryption_secrets(&mut new, &old, probe);
        assert_eq!(
            new.legacy_key(),
            Some(HEX32),
            "mode flip Aes256GcmProxy → SseKms must promote old primary into new legacy_key slot"
        );
    }

    #[test]
    fn preserve_mode_flip_explicit_null_legacy_key_disables_promotion() {
        // Escape hatch: operator explicitly passes `legacy_key: null`
        // in the body to say "discard old keys, don't preserve".
        // Must NOT auto-promote.
        let old = proxy(Some(HEX32), None);
        let mut new = kms(None);
        let probe = BackendKeyPresence {
            key_is_explicit_null: false,
            legacy_key_is_explicit_null: true,
        };
        preserve_backend_encryption_secrets(&mut new, &old, probe);
        assert_eq!(
            new.legacy_key(),
            None,
            "explicit `legacy_key: null` in body must disable auto-promotion"
        );
    }

    #[test]
    fn preserve_mode_flip_explicit_legacy_key_in_body_wins_over_promotion() {
        // Operator explicitly sets a DIFFERENT legacy_key in the
        // body. Must preserve the explicit value — not overwrite
        // it with the old primary.
        let old = proxy(Some(HEX32), None);
        let mut new = kms(Some(HEX32_B));
        let probe = BackendKeyPresence::default();
        preserve_backend_encryption_secrets(&mut new, &old, probe);
        assert_eq!(
            new.legacy_key(),
            Some(HEX32_B),
            "explicit legacy_key in body must override auto-promotion"
        );
    }

    #[test]
    fn preserve_mode_flip_proxy_to_none_auto_promotes() {
        // Recipe (D) via the UI: operator flips to mode:none but
        // forgets to paste legacy_key. Auto-promotion preserves
        // historical-read capability.
        let old = proxy(Some(HEX32), None);
        let mut new = E::None {
            legacy_key: None,
            legacy_key_id: None,
        };
        let probe = BackendKeyPresence::default();
        preserve_backend_encryption_secrets(&mut new, &old, probe);
        assert_eq!(new.legacy_key(), Some(HEX32));
    }

    #[test]
    fn preserve_same_mode_doesnt_promote_anywhere() {
        // Same-mode edit (Aes256GcmProxy → Aes256GcmProxy with a
        // rotated key): no promotion, legacy_key just preserves
        // from old → new via the same-slot preservation path.
        let old = proxy(Some(HEX32), Some(HEX32_B));
        let mut new = proxy(None, None); // redacted round-trip
        let probe = BackendKeyPresence::default();
        preserve_backend_encryption_secrets(&mut new, &old, probe);
        assert_eq!(
            new.primary_key(),
            Some(HEX32),
            "same-mode preserves primary"
        );
        assert_eq!(
            new.legacy_key(),
            Some(HEX32_B),
            "same-mode preserves legacy_key"
        );
    }
}
